<a href="https://colab.research.google.com/github/imShub/imShub/blob/master/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Basic Function

In [ ]:
import numpy as np
array1 = np.array([[2,3,34,4,7,4,7,3],
                  [2,3,34,4,7,4,7,3]])
print(array1)
print(type(array1))

[[ 2  3 34  4  7  4  7  3]
 [ 2  3 34  4  7  4  7  3]]
<class 'numpy.ndarray'>


In [ ]:
array1.shape

(2, 8)

In [ ]:
array2 = array1.mean
print(array1)

[[ 2  3 34  4  7  4  7  3]
 [ 2  3 34  4  7  4  7  3]]


In [ ]:
array1.shape

(2, 8)

In [ ]:
array1.dtype

dtype('int64')

In [ ]:
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
list1 = [12,43,45]
print(list1)

[12, 43, 45]


In [ ]:
print(list1[0 : 2])

[12, 43]


In [1]:
import numpy as np
array1 = np.array([[2,3,34,4,7,4,7,3],
                  [2,3,34,4,7,4,7,3]])
print(array1)

[[ 2  3 34  4  7  4  7  3]
 [ 2  3 34  4  7  4  7  3]]
